# Setup

In [1]:
import os
import pandas as pd
from pathlib import Path
from dotenv import load_dotenv
load_dotenv()
from helper_functions import (
    load_episodes, 
    calculate_rating_metrics,
    calculate_imdb_metrics,
    merge_metrics_dicts
)
import statsmodels.formula.api as stats

In [2]:
# Config
GEMINI_MODEL = "gemini-2.5-flash-lite"
DEBERTA_MODEL = "microsoft_deberta_v3_base_SGD_without_dropout_cls_results"
ROOT = Path(os.environ.get("PROJECT_ROOT"))
DATA_DIR = ROOT / "data"
IMDb_RATINGS_PATH = DATA_DIR / "imdb_episode_ratings.json"
OUTPUT_DIR = DATA_DIR / "modeled_episode_ratings"
DATA_SOURCES = ["labels", "gemini", "deberta"]
DATA_PATHS = {
    "labels": 
        DATA_DIR / "labeled_scenes.json",
    "deberta": 
        DATA_DIR / "DeBERTa_predictions" / "all_scenes_with_transcripts" / f"{DEBERTA_MODEL}.json",
    "gemini":
        DATA_DIR / "gemini_predictions" /  "all_scenes_with_transcripts" / f"{GEMINI_MODEL}.json",
}

# Calculate metrics using helper functions

In [3]:
# Calculate metrics using helper functions
episodes = load_episodes()
rating_metrics = calculate_rating_metrics(episodes)
imdb_metrics = calculate_imdb_metrics()
merge_metrics_dicts(rating_metrics, imdb_metrics)

# Convert merge metric dictionaries for each source into dataframes
metrics_dfs = []
for source in DATA_SOURCES:
    metrics_dfs.append(pd.json_normalize(rating_metrics[source].values()))

# Unpack metrics dataframes so we can analyze them separately
labels_metrics_df, gemini_metrics_df, deberta_metrics_df = metrics_dfs

# Analysis

## Labels
#### Starting by looking at the episodes I manually labeled

In [4]:
labels_metrics_df

,funny_mean,funny_var,funny_change,sad_mean,sad_var,sad_change,episode_id,imdb_rating_mean,imdb_rating_variance,imdb_rating_share_1,imdb_rating_share_10
0,2.020000,0.958776,0.816327,1.580000,0.575102,0.448980,1_01,8.306875,2.932065,0.022584,0.245433
1,2.173077,1.126320,0.803922,1.865385,1.216817,0.666667,3_14,9.371446,3.632755,0.037713,0.816821
2,2.156250,0.781250,0.806452,2.125000,1.532258,0.967742,5_20,9.177798,4.183887,0.040028,0.741913
3,1.731707,0.651220,0.875000,2.024390,1.824390,0.400000,1_04,8.996665,2.854143,0.024560,0.516070
4,2.200000,0.929412,0.970588,1.685714,0.692437,0.558824,2_18,8.391839,3.016799,0.026554,0.248705
5,2.368421,0.725462,0.756757,1.500000,0.527027,0.405405,4_14,8.142857,3.368442,0.027875,0.226481
6,2.545455,0.926407,1.238095,1.818182,0.632035,0.761905,6_05,7.637333,3.518251,0.033778,0.149333
7,1.911111,0.946465,0.750000,2.066667,1.063636,0.772727,1_08,8.032447,2.632458,0.022872,0.162234
8,2.750000,0.861111,1.074074,1.428571,0.253968,0.407407,4_07,7.733878,3.431220,0.033469,0.141224
9,2.709677,1.146237,0.966667,1.580645,0.851613,0.566667,5_08,8.051012,3.612782,0.035628,0.190283
10,2.472222,1.342063,1.028571,1.722222,1.063492,0.600000,3_05,8.016504,3.150515,0.030008,0.168792
11,2.285714,0.680672,0.794118,1.942857,0.878992,0.705882,6_02,8.011485,3.811189,0.035275,0.206727
12,2.138889,0.865873,0.742857,2.333333,1.485714,0.914286,4_06,8.659033,3.234887,0.028626,0.358779
13,2.366667,0.447126,0.827586,1.733333,0.685057,0.758621,5_23,7.896819,3.573189,0.036973,0.169390
14,2.542857,0.784874,0.823529,1.800000,0.635294,0.676471,4_20,8.142975,3.442171,0.033689,0.206245
15,2.194444,0.903968,0.942857,1.583333,0.421429,0.428571,3_17,7.826473,2.997330,0.029863,0.145278

#### We can see here that we only have 15 data points since I only labeled 15 episodes manually. There is some variation in our metrics. As a reminder, those are:

- Funny/Sad Mean: The mean rating of scenes in the episode
- Funny/Sad Variance: The rating variance among scenes in the episode
- Funny/Sad Change: The mean absolute value change in funny/value between scenes, measuring the oscillation in tone in the show

- IMDB Rating Mean: The mean rating of the episode by users on IMDB
- IMDB Rating Variance: The variance of episode ratings from users on IMDB
- IMDB Share 1/10: The share of ratings that are 1/10, each measuring extreme like/dislike of the episode by users on IMDB

#### Since we only have 15 data points, including all these features in a regression wouldn't give us a realistic model, so I'll just show correlations here:

In [5]:
# Correlations
labels_metrics_df.drop(columns=["episode_id"]).corr()

,funny_mean,funny_var,funny_change,sad_mean,sad_var,sad_change,imdb_rating_mean,imdb_rating_variance,imdb_rating_share_1,imdb_rating_share_10
funny_mean,1.000000,0.215088,0.540956,-0.547356,-0.604593,-0.053846,-0.563731,0.476696,0.546150,-0.432608
funny_var,0.215088,1.000000,0.345746,-0.156704,0.001333,-0.085572,0.025670,-0.172229,-0.088742,0.022432
funny_change,0.540956,0.345746,1.000000,-0.417797,-0.365835,-0.227030,-0.483972,0.018353,0.138673,-0.358063
sad_mean,-0.547356,-0.156704,-0.417797,1.000000,0.821556,0.755440,0.531915,0.072685,0.022193,0.478064
sad_var,-0.604593,0.001333,-0.365835,0.821556,1.000000,0.436923,0.767410,0.043925,-0.007594,0.691950
sad_change,-0.053846,-0.085572,-0.227030,0.755440,0.436923,1.000000,0.243224,0.459907,0.441086,0.301661
imdb_rating_mean,-0.563731,0.025670,-0.483972,0.531915,0.767410,0.243224,1.000000,0.181802,0.105562,0.954352
imdb_rating_variance,0.476696,-0.172229,0.018353,0.072685,0.043925,0.459907,0.181802,1.000000,0.922897,0.370464
imdb_rating_share_1,0.546150,-0.088742,0.138673,0.022193,-0.007594,0.441086,0.105562,0.922897,1.000000,0.321885
imdb_rating_share_10,-0.432608,0.022432,-0.358063,0.478064,0.691950,0.301661,0.954352,0.370464,0.321885,1.000000

Some themes are evident here. Among the features derived from my labels, the variance in sadness feature has the strongest correlation with both the IMDb mean and the share of users who gave a perfect rating to the episode. This helps illustrate that Scrubs' peaks are driven by emotional depth and range, even if humor carries the show for most of the time. I would've expected that the sad_change would have a stronger correlation with IMDb mean ratings and the share of perfect ratings, but thinking back on the episodes I labeled, some of the most emotional scenes lasted for more than 150 words, which we define as the unit of a scene for labeling purposes. With that in mind, it makes sense that the variance in sadness would correlate more strongly with acclaimed episodes' ratings. IMDb rating variance and the share of 1-star ratings are pretty correlated with one another, and neither seems to have a strong relationship with the sadness variables. There is actually a measured negative correlation between the mean in funny ratings and the share of 1-star ratings, but I imagine this is due to my super-fan status, and preference for more niche, character-based humor that IMDb users who haven't seen the show a million times might not pick up on. Likewise, I might have undervalued some of the slapstick, shock-value type humor that was more common in the early 2000s and lost appeal with multiple watches.

## Gemini Predictions
#### Moving onto the Gemini-based predictions for the 125 episodes with transcripts on the Scrubs Fandom Wiki site

In [6]:
gemini_metrics_df

,funny_mean,funny_var,funny_change,sad_mean,sad_var,sad_change,episode_id,imdb_rating_mean,imdb_rating_variance,imdb_rating_share_1,imdb_rating_share_10
0,2.791667,0.423759,0.511111,2.125000,1.473404,0.822222,1_01,8.306875,2.932065,0.022584,0.245433
1,2.803922,0.680784,0.400000,2.196078,1.320784,0.940000,3_14,9.371446,3.632755,0.037713,0.816821
2,2.677419,0.759140,0.758621,2.903226,1.823656,0.793103,5_20,9.177798,4.183887,0.040028,0.741913
3,2.700000,0.728205,0.605263,2.350000,1.720513,0.710526,1_04,8.996665,2.854143,0.024560,0.516070
4,2.969697,0.467803,0.419355,2.060606,1.308712,0.838710,2_18,8.391839,3.016799,0.026554,0.248705
...,...,...,...,...,...,...,...,...,...,...,...
120,3.263158,0.415363,0.540541,1.921053,1.371977,0.567568,6_03,7.752458,3.301547,0.029491,0.151028
121,2.954545,0.140693,0.238095,3.000000,1.142857,0.952381,6_04,8.026711,3.471741,0.032554,0.198664
122,3.136364,0.885281,0.952381,3.136364,1.742424,1.095238,6_06,8.641381,6.448165,0.063563,0.607376
123,3.181818,0.441558,0.571429,2.136364,1.170996,1.095238,6_07,7.940856,4.464984,0.045136,0.212451
124,3.354839,0.503226,0.700000,2.258065,1.064516,0.800000,6_13,8.025108,3.434002,0.032035,0.180952

#### It's worth testing adding in controls for season, whether an episode is a season opener, and whether an episode is a season finale

In [7]:
SEASON_LENGTHS = {1: 24, 2: 22, 3: 22, 4: 25, 5: 24, 6: 22} # No s7/8 transcripts

def add_controls(metrics_df: pd.DataFrame) -> pd.DataFrame:
    """
    Add season, episode number, and premiere/finale dummy controls to dataframe
    """
    
    # Parse episode_id into season and episode number
    season_episode = metrics_df["episode_id"].str.split("_", expand=True)
    metrics_df["season"] = season_episode[0].astype(int)
    metrics_df["episode_num"] = season_episode[1].astype(int)
    
    # Add premiere and finale dummy variables
    metrics_df["is_premiere"] = (metrics_df["episode_num"] == 1).astype(int)
    metrics_df["season_length"] = metrics_df["season"].map(SEASON_LENGTHS)
    metrics_df["is_finale"] = (metrics_df["episode_num"] == metrics_df["season_length"]).astype(int)
    
    # Return without intermediate season length and episode num vars
    return metrics_df.drop(columns=["season_length", "episode_num"])

In [8]:
gemini_metrics_df = add_controls(gemini_metrics_df)
gemini_metrics_df

,funny_mean,funny_var,funny_change,sad_mean,sad_var,sad_change,episode_id,imdb_rating_mean,imdb_rating_variance,imdb_rating_share_1,imdb_rating_share_10,season,is_premiere,is_finale
0,2.791667,0.423759,0.511111,2.125000,1.473404,0.822222,1_01,8.306875,2.932065,0.022584,0.245433,1,1,0
1,2.803922,0.680784,0.400000,2.196078,1.320784,0.940000,3_14,9.371446,3.632755,0.037713,0.816821,3,0,0
2,2.677419,0.759140,0.758621,2.903226,1.823656,0.793103,5_20,9.177798,4.183887,0.040028,0.741913,5,0,0
3,2.700000,0.728205,0.605263,2.350000,1.720513,0.710526,1_04,8.996665,2.854143,0.024560,0.516070,1,0,0
4,2.969697,0.467803,0.419355,2.060606,1.308712,0.838710,2_18,8.391839,3.016799,0.026554,0.248705,2,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
120,3.263158,0.415363,0.540541,1.921053,1.371977,0.567568,6_03,7.752458,3.301547,0.029491,0.151028,6,0,0
121,2.954545,0.140693,0.238095,3.000000,1.142857,0.952381,6_04,8.026711,3.471741,0.032554,0.198664,6,0,0
122,3.136364,0.885281,0.952381,3.136364,1.742424,1.095238,6_06,8.641381,6.448165,0.063563,0.607376,6,0,0
123,3.181818,0.441558,0.571429,2.136364,1.170996,1.095238,6_07,7.940856,4.464984,0.045136,0.212451,6,0,0
124,3.354839,0.503226,0.700000,2.258065,1.064516,0.800000,6_13,8.025108,3.434002,0.032035,0.180952,6,0,0

#### Let's try different combinations of OLS models:

In [9]:
controls = "+ is_premiere + is_finale + season"
features_options = [
    "funny_mean + sad_mean", 
    "funny_var + sad_var",
    "funny_change + sad_change",
]
dependent_var_options = [
    "imdb_rating_mean",
    "imdb_rating_variance",
    "imdb_rating_share_1",
    "imdb_rating_share_10"
]

# Build different models 
for dependent_var in dependent_var_options:
    for features in features_options:
        for with_controls in [True, False]:
            controls = controls if with_controls else ""
            model = stats.ols(f"{dependent_var} ~ {features} {controls}", 
                            data=gemini_metrics_df)
            results = model.fit()
            print(results.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:       imdb_rating_mean   R-squared:                       0.140
Model:                            OLS   Adj. R-squared:                  0.104
Method:                 Least Squares   F-statistic:                     3.863
Date:                Tue, 10 Mar 2026   Prob (F-statistic):            0.00280
Time:                        20:46:25   Log-Likelihood:                -29.101
No. Observations:                 125   AIC:                             70.20
Df Residuals:                     119   BIC:                             87.17
Df Model:                           5
Covariance Type:            nonrobust
===============================================================================
                  coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------
Intercept       9.1273      0.783     11.661      0.000       7.577      10.677
funny_mean     -0.4650      0.201     -2.317      0.022      -0.862      -0.068
sad_mean        0.1431      0.117      1.218      0.226      -0.090       0.376
is_premiere     0.0286      0.131      0.217      0.828      -0.231       0.289
is_finale       0.1638      0.144      1.138      0.258      -0.121       0.449
season          0.0218      0.020      1.096      0.275      -0.018       0.061
==============================================================================
Omnibus:                       30.579   Durbin-Watson:                   1.527
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               45.849
Skew:                           1.215   Prob(JB):                     1.11e-10
Kurtosis:                       4.702   Cond. No.                         150.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
                            OLS Regression Results
==============================================================================
Dep. Variable:       imdb_rating_mean   R-squared:                       0.122
Model:                            OLS   Adj. R-squared:                  0.108
Method:                 Least Squares   F-statistic:                     8.503
Date:                Tue, 10 Mar 2026   Prob (F-statistic):           0.000349
Time:                        20:46:25   Log-Likelihood:                -30.346
No. Observations:                 125   AIC:                             66.69
Df Residuals:                     122   BIC:                             75.18
Df Model:                           2
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept      8.7657      0.730     12.015      0.000       7.321      10.210
funny_mean    -0.3568      0.180     -1.979      0.050      -0.714    4.17e-05
sad_mean       0.1915      0.112      1.709      0.090      -0.030       0.413
==============================================================================
Omnibus:                       31.519   Durbin-Watson:                   1.512
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               47.555
Skew:                           1.252   Prob(JB):                     4.72e-11
Kurtosis:                       4.692   Cond. No.                         106.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
                            OLS Regression Results
==============================================================================
Dep. Variable:       imdb_rating_mean   R-squared:                       0.182
Model:                            OLS   Adj. R-squared:                  0.169
Method:                 Least Squares   F-statistic:                     13.57
Date:                Tue, 10 Mar 2026   Prob (F-statistic):           4.77e-06
Time:                        20:46:25   Log-Likelihood:                -25.948
No. Observations:                 125   AIC:                             57.90
Df Residuals:                     122   BIC:                             66.38
Df Model:                           2
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept      7.5447      0.104     72.296      0.000       7.338       7.751
funny_var      0.2201      0.151      1.458      0.147      -0.079       0.519
sad_var        0.3454      0.090      3.849      0.000       0.168       0.523
==============================================================================
Omnibus:                       33.970   Durbin-Watson:                   1.564
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               54.577
Skew:                           1.296   Prob(JB):                     1.41e-12
Kurtosis:                       4.939   Cond. No.                         9.80
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
                            OLS Regression Results
==============================================================================
Dep. Variable:       imdb_rating_mean   R-squared:                       0.182
Model:                            OLS   Adj. R-squared:                  0.169
Method:                 Least Squares   F-statistic:                     13.57
Date:                Tue, 10 Mar 2026   Prob (F-statistic):           4.77e-06
Time:                        20:46:25   Log-Likelihood:                -25.948
No. Observations:                 125   AIC:                             57.90
Df Residuals:                     122   BIC:                             66.38
Df Model:                           2
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept      7.5447      0.104     72.296      0.000       7.338       7.751
funny_var      0.2201      0.151      1.458      0.147      -0.079       0.519
sad_var        0.3454      0.090      3.849      0.000       0.168       0.523
==============================================================================
Omnibus:                       33.970   Durbin-Watson:                   1.564
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               54.577
Skew:                           1.296   Prob(JB):                     1.41e-12
Kurtosis:                       4.939   Cond. No.                         9.80
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
                            OLS Regression Results
==============================================================================
Dep. Variable:       imdb_rating_mean   R-squared:                       0.004
Model:                            OLS   Adj. R-squared:                 -0.012
Method:                 Least Squares   F-statistic:                    0.2660
Date:                Tue, 10 Mar 2026   Prob (F-statistic):              0.767
Time:                        20:46:25   Log-Likelihood:                -38.230
No. Observations:                 125   AIC:                             82.46
Df Residuals:                     122   BIC:                             90.94
Df Model:                           2
Covariance Type:            nonrobust
================================================================================
                   coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------
Intercept        7.9877      0.172     46.341      0.000       7.646       8.329
funny_change     0.1344      0.190      0.708      0.480      -0.241       0.510
sad_change       0.0065      0.182      0.036      0.972      -0.354       0.367
==============================================================================
Omnibus:                       44.461   Durbin-Watson:                   1.424
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               85.305
Skew:                           1.577   Prob(JB):                     2.99e-19
Kurtosis:                       5.536   Cond. No.                         11.5
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
                            OLS Regression Results
==============================================================================
Dep. Variable:       imdb_rating_mean   R-squared:                       0.004
Model:                            OLS   Adj. R-squared:                 -0.012
Method:                 Least Squares   F-statistic:                    0.2660
Date:                Tue, 10 Mar 2026   Prob (F-statistic):              0.767
Time:                        20:46:25   Log-Likelihood:                -38.230
No. Observations:                 125   AIC:                             82.46
Df Residuals:                     122   BIC:                             90.94
Df Model:                           2
Covariance Type:            nonrobust
================================================================================
                   coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------
Intercept        7.9877      0.172     46.341      0.000       7.646       8.329
funny_change     0.1344      0.190      0.708      0.480      -0.241       0.510
sad_change       0.0065      0.182      0.036      0.972      -0.354       0.367
==============================================================================
Omnibus:                       44.461   Durbin-Watson:                   1.424
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               85.305
Skew:                           1.577   Prob(JB):                     2.99e-19
Kurtosis:                       5.536   Cond. No.                         11.5
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
                             OLS Regression Results
================================================================================
Dep. Variable:     imdb_rating_variance   R-squared:                       0.177
Model:                              OLS   Adj. R-squared:                  0.163
Method:                   Least Squares   F-statistic:                     13.08
Date:                  Tue, 10 Mar 2026   Prob (F-statistic):           7.16e-06
Time:                          20:46:25   Log-Likelihood:                -75.821
No. Observations:                   125   AIC:                             157.6
Df Residuals:                       122   BIC:                             166.1
Df Model:                             2
Covariance Type:              nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept     -1.8315      1.050     -1.745      0.084      -3.909       0.247
funny_mean     1.0935      0.259      4.216      0.000       0.580       1.607
sad_mean       0.7809      0.161      4.844      0.000       0.462       1.100
==============================================================================
Omnibus:                       47.628   Durbin-Watson:                   1.261
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              191.272
Skew:                           1.276   Prob(JB):                     2.92e-42
Kurtosis:                       8.497   Cond. No.                         106.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
                             OLS Regression Results
================================================================================
Dep. Variable:     imdb_rating_variance   R-squared:                       0.177
Model:                              OLS   Adj. R-squared:                  0.163
Method:                   Least Squares   F-statistic:                     13.08
Date:                  Tue, 10 Mar 2026   Prob (F-statistic):           7.16e-06
Time:                          20:46:25   Log-Likelihood:                -75.821
No. Observations:                   125   AIC:                             157.6
Df Residuals:                       122   BIC:                             166.1
Df Model:                             2
Covariance Type:              nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept     -1.8315      1.050     -1.745      0.084      -3.909       0.247
funny_mean     1.0935      0.259      4.216      0.000       0.580       1.607
sad_mean       0.7809      0.161      4.844      0.000       0.462       1.100
==============================================================================
Omnibus:                       47.628   Durbin-Watson:                   1.261
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              191.272
Skew:                           1.276   Prob(JB):                     2.92e-42
Kurtosis:                       8.497   Cond. No.                         106.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
                             OLS Regression Results
================================================================================
Dep. Variable:     imdb_rating_variance   R-squared:                       0.036
Model:                              OLS   Adj. R-squared:                  0.020
Method:                   Least Squares   F-statistic:                     2.291
Date:                  Tue, 10 Mar 2026   Prob (F-statistic):              0.106
Time:                          20:46:25   Log-Likelihood:                -85.656
No. Observations:                   125   AIC:                             177.3
Df Residuals:                       122   BIC:                             185.8
Df Model:                             2
Covariance Type:              nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept      2.8926      0.168     17.192      0.000       2.560       3.226
funny_var      0.0599      0.243      0.246      0.806      -0.422       0.542
sad_var        0.2605      0.145      1.801      0.074      -0.026       0.547
==============================================================================
Omnibus:                       81.739   Durbin-Watson:                   0.974
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              749.282
Skew:                           2.044   Prob(JB):                    1.97e-163
Kurtosis:                      14.276   Cond. No.                         9.80
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
                             OLS Regression Results
================================================================================
Dep. Variable:     imdb_rating_variance   R-squared:                       0.036
Model:                              OLS   Adj. R-squared:                  0.020
Method:                   Least Squares   F-statistic:                     2.291
Date:                  Tue, 10 Mar 2026   Prob (F-statistic):              0.106
Time:                          20:46:25   Log-Likelihood:                -85.656
No. Observations:                   125   AIC:                             177.3
Df Residuals:                       122   BIC:                             185.8
Df Model:                             2
Covariance Type:              nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept      2.8926      0.168     17.192      0.000       2.560       3.226
funny_var      0.0599      0.243      0.246      0.806      -0.422       0.542
sad_var        0.2605      0.145      1.801      0.074      -0.026       0.547
==============================================================================
Omnibus:                       81.739   Durbin-Watson:                   0.974
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              749.282
Skew:                           2.044   Prob(JB):                    1.97e-163
Kurtosis:                      14.276   Cond. No.                         9.80
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
                             OLS Regression Results
================================================================================
Dep. Variable:     imdb_rating_variance   R-squared:                       0.030
Model:                              OLS   Adj. R-squared:                  0.015
Method:                   Least Squares   F-statistic:                     1.912
Date:                  Tue, 10 Mar 2026   Prob (F-statistic):              0.152
Time:                          20:46:25   Log-Likelihood:                -86.031
No. Observations:                   125   AIC:                             178.1
Df Residuals:                       122   BIC:                             186.5
Df Model:                             2
Covariance Type:              nonrobust
================================================================================
                   coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------
Intercept        2.7637      0.253     10.938      0.000       2.264       3.264
funny_change     0.1278      0.278      0.459      0.647      -0.423       0.678
sad_change       0.4750      0.267      1.779      0.078      -0.053       1.003
==============================================================================
Omnibus:                       80.651   Durbin-Watson:                   1.067
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              719.448

#### Let's take a closer look at the two strongest models: sadness variance predicting mean IMDb ratings, and mean funniness/sadness predicting IMDb rating variance:

In [10]:
target_models = [
    ("imdb_rating_mean", "funny_var + sad_var"),
    ("imdb_rating_variance", "funny_mean + sad_mean"),
]

for dependent_var, features in target_models:
    model = stats.ols(f"{dependent_var} ~ {features}", data=gemini_metrics_df)
    results = model.fit()
    print(results.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:       imdb_rating_mean   R-squared:                       0.182
Model:                            OLS   Adj. R-squared:                  0.169
Method:                 Least Squares   F-statistic:                     13.57
Date:                Tue, 10 Mar 2026   Prob (F-statistic):           4.77e-06
Time:                        20:46:25   Log-Likelihood:                -25.948
No. Observations:                 125   AIC:                             57.90
Df Residuals:                     122   BIC:                             66.38
Df Model:                           2
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept      7.5447      0.104     72.296      0.000       7.338       7.751
funny_var      0.2201      0.151      1.458      0.147      -0.079       0.519
sad_var        0.3454      0.090      3.849      0.000       0.168       0.523
==============================================================================
Omnibus:                       33.970   Durbin-Watson:                   1.564
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               54.577
Skew:                           1.296   Prob(JB):                     1.41e-12
Kurtosis:                       4.939   Cond. No.                         9.80
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
                             OLS Regression Results
================================================================================
Dep. Variable:     imdb_rating_variance   R-squared:                       0.177
Model:                              OLS   Adj. R-squared:                  0.163
Method:                   Least Squares   F-statistic:                     13.08
Date:                  Tue, 10 Mar 2026   Prob (F-statistic):           7.16e-06
Time:                          20:46:25   Log-Likelihood:                -75.821
No. Observations:                   125   AIC:                             157.6
Df Residuals:                       122   BIC:                             166.1
Df Model:                             2
Covariance Type:              nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept     -1.8315      1.050     -1.745      0.084      -3.909       0.247
funny_mean     1.0935      0.259      4.216      0.000       0.580       1.607
sad_mean       0.7809      0.161      4.844      0.000       0.462       1.100
==============================================================================
Omnibus:                       47.628   Durbin-Watson:                   1.261
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              191.272
Skew:                           1.276   Prob(JB):                     2.92e-42
Kurtosis:                       8.497   Cond. No.                         106.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

As we saw with the data that I labeled, the regression results using our Gemini-generated ratings tell a pretty consistent story across different models. Sadness variance is the only feature that consistently appears as a predictor of IMDb mean rating and the share of IMDb ratings of 10, significant at the .01 level.  In our simple model predicting the mean IMDb rating with funny/sad variances and without controls, a one-unit increase in sadness variance is associated with a 0.35 point increase in IMDb mean rating, holding funny variance constant.

The results around IMDb rating polarization are a little more interesting. Both the funny mean and sad mean features have significant positive associations with IMDb rating variance and the share of IMDb users who gave 1-star ratings. In the simple model predicting IMDb rating variance with funny/sad means without controls, a one-unit increase in funny mean is associated with a 1.09 point increase in IMDb rating variance, and a one-unit increase in sad mean is associated with a 0.78 point increase, both significant at the .01 level. Thinking about these results, it seems that some IMDb users enjoy when episodes are more intense and/or funny, while others prefer a more balanced pace to the episode.  

Again, my oscillation variables do not perform well as predictors. Scene-to-scene funniness or sadness switching isn't significantly associated with any dependent variable. I think the variance does a better job of measuring the "gut punch" feeling, for the scene identification reasons discussed above.

Also, it's worth noting that even the best-performing models explain only about 17% or 18% of the variation in IMDb dependent variables

## DeBERTa Predictions
#### Moving onto the DeBERTa-based predictions for the 125 episodes with transcripts on the Scrubs Fandom wiki site

In [11]:
# Build different models 
for dependent_var in dependent_var_options:
    for features in features_options:
        for with_controls in [True, False]:
            controls = controls if with_controls else ""
            model = stats.ols(f"{dependent_var} ~ {features} {controls}", 
                            data=deberta_metrics_df)
            results = model.fit()
            print(results.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:       imdb_rating_mean   R-squared:                       0.040
Model:                            OLS   Adj. R-squared:                  0.024
Method:                 Least Squares   F-statistic:                     2.530
Date:                Tue, 10 Mar 2026   Prob (F-statistic):             0.0838
Time:                        20:46:25   Log-Likelihood:                -35.962
No. Observations:                 125   AIC:                             77.92
Df Residuals:                     122   BIC:                             86.41
Df Model:                           2
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept      8.7353      0.297     29.374      0.000       8.147       9.324
funny_mean    -0.2948      0.757     -0.390      0.698      -1.793       1.203
sad_mean       0.1992      0.932      0.214      0.831      -1.645       2.044
==============================================================================
Omnibus:                       32.310   Durbin-Watson:                   1.845
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               47.557
Skew:                           1.328   Prob(JB):                     4.71e-11
Kurtosis:                       4.439   Cond. No.                         264.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
                            OLS Regression Results
==============================================================================
Dep. Variable:       imdb_rating_mean   R-squared:                       0.040
Model:                            OLS   Adj. R-squared:                  0.024
Method:                 Least Squares   F-statistic:                     2.530
Date:                Tue, 10 Mar 2026   Prob (F-statistic):             0.0838
Time:                        20:46:25   Log-Likelihood:                -35.962
No. Observations:                 125   AIC:                             77.92
Df Residuals:                     122   BIC:                             86.41
Df Model:                           2
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept      8.7353      0.297     29.374      0.000       8.147       9.324
funny_mean    -0.2948      0.757     -0.390      0.698      -1.793       1.203
sad_mean       0.1992      0.932      0.214      0.831      -1.645       2.044
==============================================================================
Omnibus:                       32.310   Durbin-Watson:                   1.845
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               47.557
Skew:                           1.328   Prob(JB):                     4.71e-11
Kurtosis:                       4.439   Cond. No.                         264.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
                            OLS Regression Results
==============================================================================
Dep. Variable:       imdb_rating_mean   R-squared:                       0.067
Model:                            OLS   Adj. R-squared:                  0.052
Method:                 Least Squares   F-statistic:                     4.383
Date:                Tue, 10 Mar 2026   Prob (F-statistic):             0.0145
Time:                        20:46:25   Log-Likelihood:                -34.165
No. Observations:                 125   AIC:                             74.33
Df Residuals:                     122   BIC:                             82.81
Df Model:                           2
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept      8.0352      0.031    257.976      0.000       7.974       8.097
funny_var     -1.2214      0.851     -1.435      0.154      -2.906       0.463
sad_var        3.4336      1.353      2.537      0.012       0.754       6.113
==============================================================================
Omnibus:                       30.406   Durbin-Watson:                   1.846
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               43.185
Skew:                           1.286   Prob(JB):                     4.19e-10
Kurtosis:                       4.295   Cond. No.                         54.0
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
                            OLS Regression Results
==============================================================================
Dep. Variable:       imdb_rating_mean   R-squared:                       0.067
Model:                            OLS   Adj. R-squared:                  0.052
Method:                 Least Squares   F-statistic:                     4.383
Date:                Tue, 10 Mar 2026   Prob (F-statistic):             0.0145
Time:                        20:46:25   Log-Likelihood:                -34.165
No. Observations:                 125   AIC:                             74.33
Df Residuals:                     122   BIC:                             82.81
Df Model:                           2
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept      8.0352      0.031    257.976      0.000       7.974       8.097
funny_var     -1.2214      0.851     -1.435      0.154      -2.906       0.463
sad_var        3.4336      1.353      2.537      0.012       0.754       6.113
==============================================================================
Omnibus:                       30.406   Durbin-Watson:                   1.846
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               43.185
Skew:                           1.286   Prob(JB):                     4.19e-10
Kurtosis:                       4.295   Cond. No.                         54.0
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
                            OLS Regression Results
==============================================================================
Dep. Variable:       imdb_rating_mean   R-squared:                       0.050
Model:                            OLS   Adj. R-squared:                  0.034
Method:                 Least Squares   F-statistic:                     3.206
Date:                Tue, 10 Mar 2026   Prob (F-statistic):             0.0440
Time:                        20:46:25   Log-Likelihood:                -35.301
No. Observations:                 125   AIC:                             76.60
Df Residuals:                     122   BIC:                             85.09
Df Model:                           2
Covariance Type:            nonrobust
================================================================================
                   coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------
Intercept        8.0399      0.032    250.287      0.000       7.976       8.104
funny_change    -0.3502      0.640     -0.547      0.585      -1.617       0.917
sad_change       1.3752      0.834      1.649      0.102      -0.275       3.026
==============================================================================
Omnibus:                       31.256   Durbin-Watson:                   1.841
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               44.968
Skew:                           1.312   Prob(JB):                     1.72e-10
Kurtosis:                       4.322   Cond. No.                         35.2
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
                            OLS Regression Results
==============================================================================
Dep. Variable:       imdb_rating_mean   R-squared:                       0.050
Model:                            OLS   Adj. R-squared:                  0.034
Method:                 Least Squares   F-statistic:                     3.206
Date:                Tue, 10 Mar 2026   Prob (F-statistic):             0.0440
Time:                        20:46:25   Log-Likelihood:                -35.301
No. Observations:                 125   AIC:                             76.60
Df Residuals:                     122   BIC:                             85.09
Df Model:                           2
Covariance Type:            nonrobust
================================================================================
                   coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------
Intercept        8.0399      0.032    250.287      0.000       7.976       8.104
funny_change    -0.3502      0.640     -0.547      0.585      -1.617       0.917
sad_change       1.3752      0.834      1.649      0.102      -0.275       3.026
==============================================================================
Omnibus:                       31.256   Durbin-Watson:                   1.841
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               44.968
Skew:                           1.312   Prob(JB):                     1.72e-10
Kurtosis:                       4.322   Cond. No.                         35.2
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
                             OLS Regression Results
================================================================================
Dep. Variable:     imdb_rating_variance   R-squared:                       0.008
Model:                              OLS   Adj. R-squared:                 -0.008
Method:                   Least Squares   F-statistic:                    0.4805
Date:                  Tue, 10 Mar 2026   Prob (F-statistic):              0.620
Time:                          20:46:25   Log-Likelihood:                -87.470
No. Observations:                   125   AIC:                             180.9
Df Residuals:                       122   BIC:                             189.4
Df Model:                             2
Covariance Type:              nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept      3.6369      0.449      8.099      0.000       2.748       4.526
funny_mean    -0.6479      1.142     -0.567      0.572      -2.909       1.614
sad_mean       0.7067      1.407      0.502      0.616      -2.079       3.492
==============================================================================
Omnibus:                       94.069   Durbin-Watson:                   0.861
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             1077.504
Skew:                           2.385   Prob(JB):                    1.05e-234
Kurtosis:                      16.570   Cond. No.                         264.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
                             OLS Regression Results
================================================================================
Dep. Variable:     imdb_rating_variance   R-squared:                       0.008
Model:                              OLS   Adj. R-squared:                 -0.008
Method:                   Least Squares   F-statistic:                    0.4805
Date:                  Tue, 10 Mar 2026   Prob (F-statistic):              0.620
Time:                          20:46:25   Log-Likelihood:                -87.470
No. Observations:                   125   AIC:                             180.9
Df Residuals:                       122   BIC:                             189.4
Df Model:                             2
Covariance Type:              nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept      3.6369      0.449      8.099      0.000       2.748       4.526
funny_mean    -0.6479      1.142     -0.567      0.572      -2.909       1.614
sad_mean       0.7067      1.407      0.502      0.616      -2.079       3.492
==============================================================================
Omnibus:                       94.069   Durbin-Watson:                   0.861
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             1077.504
Skew:                           2.385   Prob(JB):                    1.05e-234
Kurtosis:                      16.570   Cond. No.                         264.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
                             OLS Regression Results
================================================================================
Dep. Variable:     imdb_rating_variance   R-squared:                       0.006
Model:                              OLS   Adj. R-squared:                 -0.010
Method:                   Least Squares   F-statistic:                    0.3825
Date:                  Tue, 10 Mar 2026   Prob (F-statistic):              0.683
Time:                          20:46:25   Log-Likelihood:                -87.569
No. Observations:                   125   AIC:                             181.1
Df Residuals:                       122   BIC:                             189.6
Df Model:                             2
Covariance Type:              nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept      3.2282      0.048     67.606      0.000       3.134       3.323
funny_var      0.4634      1.305      0.355      0.723      -2.119       3.046
sad_var        0.1898      2.075      0.091      0.927      -3.918       4.297
==============================================================================
Omnibus:                       93.497   Durbin-Watson:                   0.862
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             1058.357
Skew:                           2.369   Prob(JB):                    1.52e-230
Kurtosis:                      16.445   Cond. No.                         54.0
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
                             OLS Regression Results
================================================================================
Dep. Variable:     imdb_rating_variance   R-squared:                       0.006
Model:                              OLS   Adj. R-squared:                 -0.010
Method:                   Least Squares   F-statistic:                    0.3825
Date:                  Tue, 10 Mar 2026   Prob (F-statistic):              0.683
Time:                          20:46:25   Log-Likelihood:                -87.569
No. Observations:                   125   AIC:                             181.1
Df Residuals:                       122   BIC:                             189.6
Df Model:                             2
Covariance Type:              nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept      3.2282      0.048     67.606      0.000       3.134       3.323
funny_var      0.4634      1.305      0.355      0.723      -2.119       3.046
sad_var        0.1898      2.075      0.091      0.927      -3.918       4.297
==============================================================================
Omnibus:                       93.497   Durbin-Watson:                   0.862
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             1058.357
Skew:                           2.369   Prob(JB):                    1.52e-230
Kurtosis:                      16.445   Cond. No.                         54.0
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
                             OLS Regression Results
================================================================================
Dep. Variable:     imdb_rating_variance   R-squared:                       0.007
Model:                              OLS   Adj. R-squared:                 -0.010
Method:                   Least Squares   F-statistic:                    0.4071
Date:                  Tue, 10 Mar 2026   Prob (F-statistic):              0.666
Time:                          20:46:25   Log-Likelihood:                -87.544
No. Observations:                   125   AIC:                             181.1
Df Residuals:                       122   BIC:                             189.6
Df Model:                             2
Covariance Type:              nonrobust
================================================================================
                   coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------
Intercept        3.2342      0.049     66.289      0.000       3.138       3.331
funny_change     0.6056      0.972      0.623      0.534      -1.319       2.530
sad_change      -0.3052      1.266     -0.241      0.810      -2.812       2.202
==============================================================================
Omnibus:                       93.005   Durbin-Watson:                   0.866
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             1043.130
Skew:                           2.355   Prob(JB):                    3.07e-227
Kurtosis:                      16.345   Cond. No.                         35.2
==============================================================================

Notes:

Unfortunately, the results using DeBERTa predictions were pretty bleak. Most of our predictors had high p-values across all models, and the few models that did produce results significant at the .05 level came with very large standard errors, suggesting they were not meaningful. For example, in the model predicting mean IMDb rating with funny and sad variance, sad variance had a coefficient of 3.43 — nearly ten times the 0.35 we saw in the equivalent Gemini model, but with a standard error of 1.35. The results from the DeBERTa model are also largely inconsistent with the Gemini results. For example, the DeBERTa model predicting IMDb rating variance with funny and sad means shows funny mean negatively associated with rating variance, the opposite of what Gemini found. These factors, particularly the high p-values, suggest that the DeBERTa model performed more poorly than the Gemini model in correctly predicting how funny and sad scenes are.